DELETE FROM parameters;
DELETE FROM batches;
INSERT INTO batches (code, measured_at, user_code) VALUES ('BATCH-001', '2026-09-01 14:00:00', 'USR-001');
INSERT INTO batches (code, measured_at, user_code) VALUES ('BATCH-002', '2026-09-01 20:00:00', 'USR-002');
INSERT INTO batches (code, measured_at, user_code) VALUES ('BATCH-003', '2026-09-02 02:00:00', 'USR-003');
INSERT INTO batches (code, measured_at, user_code) VALUES ('BATCH-004', '2026-09-02 08:00:00', 'USR-004');
INSERT INTO batches (code, measured_at, user_code) VALUES ('BATCH-005', '2026-09-02 14:00:00', 'USR-005');
INSERT INTO batches (code, measured_at, user_code) VALUES ('BATCH-006', '2026-09-02 20:00:00', 'USR-001');
INSERT INTO batches (code, measured_at, user_code) VALUES ('BATCH-007', '2026-09-03 02:00:00', 'USR-002');
INSERT INTO batches (code, measured_at, user_code) VALUES ('BATCH-008', '2026-09-03 08:00:00', 'USR-003');
INSERT INTO batches (code, measured_at, user_code) VALUES ('BATCH-009', '2026-09-03 14:00:00', 'USR-004');
INSERT INTO batches (code, measured_at, user_code) VALUES ('BATCH-010', '2026-09-03 20:00:00', 'USR-005');
INSERT INTO batches (code, measured_at, user_code) VALUES ('BATCH-011', '2026-09-04 02:00:00', 'USR-001');
INSERT INTO batches (code, measured_at, user_code) VALUES ('BATCH-012', '2026-09-04 08:00:00', 'USR-002');
INSERT INTO batches (code, measured_at, user_code) VALUES ('BATCH-013', '2026-09-04 14:00:00', 'USR-003');
INSERT INTO batches (code, measured_at, user_code) VALUES ('BATCH-014', '2026-09-04 20:00:00', 'USR-004');
INSERT INTO batches (code, measured_at, user_code) VALUES ('BATCH-015', '2026-09-05 02:00:00', 'USR-005');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-001', 148.0, 'TYPE-001', 'UNIT-001', 'BATCH-001');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-002', 30.0, 'TYPE-002', 'UNIT-002', 'BATCH-001');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-003', 740.0, 'TYPE-003', 'UNIT-003', 'BATCH-001');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-004', 45, 'TYPE-004', 'UNIT-004', 'BATCH-001');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-005', 5.5, 'TYPE-005', 'UNIT-005', 'BATCH-001');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-006', 110.3, 'TYPE-001', 'UNIT-001', 'BATCH-002');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-007', 15.7, 'TYPE-002', 'UNIT-002', 'BATCH-002');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-008', 760.0, 'TYPE-003', 'UNIT-003', 'BATCH-002');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-009', 12, 'TYPE-004', 'UNIT-004', 'BATCH-002');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-010', 1.1, 'TYPE-005', 'UNIT-005', 'BATCH-002');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-011', 142.7, 'TYPE-001', 'UNIT-001', 'BATCH-003');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-012', 22.5, 'TYPE-002', 'UNIT-002', 'BATCH-003');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-013', 745.3, 'TYPE-003', 'UNIT-003', 'BATCH-003');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-014', 30, 'TYPE-004', 'UNIT-004', 'BATCH-003');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-015', 8.0, 'TYPE-005', 'UNIT-005', 'BATCH-003');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-016', 120.5, 'TYPE-001', 'UNIT-001', 'BATCH-004');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-017', 18.3, 'TYPE-002', 'UNIT-002', 'BATCH-004');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-018', 752.1, 'TYPE-003', 'UNIT-003', 'BATCH-004');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-019', 58, 'TYPE-004', 'UNIT-004', 'BATCH-004');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-020', 4.3, 'TYPE-005', 'UNIT-005', 'BATCH-004');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-021', 135.2, 'TYPE-001', 'UNIT-001', 'BATCH-005');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-022', -5.1, 'TYPE-002', 'UNIT-002', 'BATCH-005');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-023', 768.5, 'TYPE-003', 'UNIT-003', 'BATCH-005');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-024', 3, 'TYPE-004', 'UNIT-004', 'BATCH-005');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-025', 3.2, 'TYPE-005', 'UNIT-005', 'BATCH-005');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-026', 148.0, 'TYPE-001', 'UNIT-001', 'BATCH-006');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-027', 30.0, 'TYPE-002', 'UNIT-002', 'BATCH-006');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-028', 740.0, 'TYPE-003', 'UNIT-003', 'BATCH-006');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-029', 45, 'TYPE-004', 'UNIT-004', 'BATCH-006');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-030', 5.5, 'TYPE-005', 'UNIT-005', 'BATCH-006');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-031', 110.3, 'TYPE-001', 'UNIT-001', 'BATCH-007');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-032', 15.7, 'TYPE-002', 'UNIT-002', 'BATCH-007');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-033', 760.0, 'TYPE-003', 'UNIT-003', 'BATCH-007');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-034', 12, 'TYPE-004', 'UNIT-004', 'BATCH-007');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-035', 1.1, 'TYPE-005', 'UNIT-005', 'BATCH-007');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-036', 142.7, 'TYPE-001', 'UNIT-001', 'BATCH-008');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-037', 22.5, 'TYPE-002', 'UNIT-002', 'BATCH-008');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-038', 745.3, 'TYPE-003', 'UNIT-003', 'BATCH-008');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-039', 30, 'TYPE-004', 'UNIT-004', 'BATCH-008');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-040', 8.0, 'TYPE-005', 'UNIT-005', 'BATCH-008');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-041', 120.5, 'TYPE-001', 'UNIT-001', 'BATCH-009');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-042', 18.3, 'TYPE-002', 'UNIT-002', 'BATCH-009');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-043', 752.1, 'TYPE-003', 'UNIT-003', 'BATCH-009');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-044', 58, 'TYPE-004', 'UNIT-004', 'BATCH-009');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-045', 4.3, 'TYPE-005', 'UNIT-005', 'BATCH-009');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-046', 135.2, 'TYPE-001', 'UNIT-001', 'BATCH-010');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-047', -5.1, 'TYPE-002', 'UNIT-002', 'BATCH-010');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-048', 768.5, 'TYPE-003', 'UNIT-003', 'BATCH-010');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-049', 3, 'TYPE-004', 'UNIT-004', 'BATCH-010');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-050', 3.2, 'TYPE-005', 'UNIT-005', 'BATCH-010');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-051', 148.0, 'TYPE-001', 'UNIT-001', 'BATCH-011');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-052', 30.0, 'TYPE-002', 'UNIT-002', 'BATCH-011');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-053', 740.0, 'TYPE-003', 'UNIT-003', 'BATCH-011');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-054', 45, 'TYPE-004', 'UNIT-004', 'BATCH-011');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-055', 5.5, 'TYPE-005', 'UNIT-005', 'BATCH-011');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-056', 110.3, 'TYPE-001', 'UNIT-001', 'BATCH-012');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-057', 15.7, 'TYPE-002', 'UNIT-002', 'BATCH-012');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-058', 760.0, 'TYPE-003', 'UNIT-003', 'BATCH-012');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-059', 12, 'TYPE-004', 'UNIT-004', 'BATCH-012');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-060', 1.1, 'TYPE-005', 'UNIT-005', 'BATCH-012');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-061', 142.7, 'TYPE-001', 'UNIT-001', 'BATCH-013');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-062', 22.5, 'TYPE-002', 'UNIT-002', 'BATCH-013');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-063', 745.3, 'TYPE-003', 'UNIT-003', 'BATCH-013');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-064', 30, 'TYPE-004', 'UNIT-004', 'BATCH-013');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-065', 8.0, 'TYPE-005', 'UNIT-005', 'BATCH-013');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-066', 120.5, 'TYPE-001', 'UNIT-001', 'BATCH-014');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-067', 18.3, 'TYPE-002', 'UNIT-002', 'BATCH-014');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-068', 752.1, 'TYPE-003', 'UNIT-003', 'BATCH-014');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-069', 58, 'TYPE-004', 'UNIT-004', 'BATCH-014');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-070', 4.3, 'TYPE-005', 'UNIT-005', 'BATCH-014');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-071', 135.2, 'TYPE-001', 'UNIT-001', 'BATCH-015');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-072', -5.1, 'TYPE-002', 'UNIT-002', 'BATCH-015');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-073', 768.5, 'TYPE-003', 'UNIT-003', 'BATCH-015');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-074', 3, 'TYPE-004', 'UNIT-004', 'BATCH-015');
INSERT INTO parameters (code, parameter_value, parameter_type_code, measurement_unit_code, batch_code) VALUES ('PARAM-075', 3.2, 'TYPE-005', 'UNIT-005', 'BATCH-015');