version: "3.0"
services:
  # https://hub.docker.com/_/postgres

  postgres:
    user: root
    image: postgres:16.3
    container_name: "postgres"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
     - 15435:5432
    networks:
     - pgdata

  pgadmin:
    user: root
    container_name: "pgadmin"
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRESQL_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRESQL_PASS}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin  
      - ./scripts:/scripts    
    networks:
      - pgdata  
    restart: always
    depends_on:
    - postgres

networks:
  pgdata:

